In [1]:
import glob
import pandas as pd
catfn = glob.glob("train/cat.*.jpg")
dogfn = glob.glob("train/dog.*.jpg")
catans = [0] * len(catfn)
dogans = [1] * len(dogfn)
df = pd.DataFrame({
    "path":catfn + dogfn,
    "ans":catans + dogans
})
df

ans                 path
0        0   train/cat.5077.jpg
1        0   train/cat.2718.jpg
2        0  train/cat.10151.jpg
3        0   train/cat.3406.jpg
4        0   train/cat.4369.jpg
5        0   train/cat.7660.jpg
6        0   train/cat.8553.jpg
7        0   train/cat.9895.jpg
8        0   train/cat.1211.jpg
9        0   train/cat.6218.jpg
10       0   train/cat.1577.jpg
11       0  train/cat.12020.jpg
12       0   train/cat.7106.jpg
13       0   train/cat.8235.jpg
14       0    train/cat.952.jpg
15       0   train/cat.3360.jpg
16       0  train/cat.11529.jpg
17       0  train/cat.10637.jpg
18       0   train/cat.5711.jpg
19       0    train/cat.946.jpg
20       0   train/cat.3374.jpg
21       0  train/cat.10623.jpg
22       0   train/cat.5705.jpg
23       0   train/cat.1563.jpg
24       0  train/cat.12034.jpg
25       0   train/cat.7112.jpg
26       0   train/cat.8221.jpg
27       0   train/cat.7674.jpg
28       0   train/cat.8547.jpg
29       0   train/cat.9881.jpg
...    ...                  ...
24970    1  train/dog.12406.jpg
24971    1    train/dog.778.jpg
24972    1   train/dog.3149.jpg
24973    1   train/dog.4626.jpg
24974    1  train/dog.10211.jpg
24975    1   train/dog.5538.jpg
24976    1   train/dog.2257.jpg
24977    1   train/dog.2531.jpg
24978    1  train/dog.10577.jpg
24979    1  train/dog.11669.jpg
24980    1   train/dog.4140.jpg
24981    1   train/dog.7449.jpg
24982    1  train/dog.12360.jpg
24983    1   train/dog.9464.jpg
24984    1   train/dog.6757.jpg
24985    1   train/dog.1038.jpg
24986    1  train/dog.12374.jpg
24987    1   train/dog.9470.jpg
24988    1   train/dog.6743.jpg
24989    1   train/dog.2525.jpg
24990    1  train/dog.10563.jpg
24991    1   train/dog.4154.jpg
24992    1   train/dog.4632.jpg
24993    1  train/dog.10205.jpg
24994    1   train/dog.2243.jpg
24995    1   train/dog.9316.jpg
24996    1   train/dog.6025.jpg
24997    1   train/dog.8008.jpg
24998    1   train/dog.1992.jpg
24999    1  train/dog.12412.jpg

[25000 rows x 2 columns]

In [2]:
import ssl
ssl._create_default_https_context = ssl._create_unverified_context

In [3]:
from keras.applications.vgg16 import VGG16
vgg = VGG16(include_top=False, input_shape=(224, 224, 3))
vgg.summary()

Using TensorFlow backend.
/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/tensorflow/python/framework/dtypes.py:519: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_qint8 = np.dtype([("qint8", np.int8, 1)])
/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/tensorflow/python/framework/dtypes.py:520: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_quint8 = np.dtype([("quint8", np.uint8, 1)])
/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/tensorflow/python/framework/dtypes.py:521: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_qint16 = np.dtype([(

_________________________________________________________________
Layer (type)                 Output Shape              Param #   
input_1 (InputLayer)         (None, 224, 224, 3)       0         
_________________________________________________________________
block1_conv1 (Conv2D)        (None, 224, 224, 64)      1792      
_________________________________________________________________
block1_conv2 (Conv2D)        (None, 224, 224, 64)      36928     
_________________________________________________________________
block1_pool (MaxPooling2D)   (None, 112, 112, 64)      0         
_________________________________________________________________
block2_conv1 (Conv2D)        (None, 112, 112, 128)     73856     
_________________________________________________________________
block2_conv2 (Conv2D)        (None, 112, 112, 128)     147584    
_________________________________________________________________
block2_pool (MaxPooling2D)   (None, 56, 56, 128)       0         
__________

In [4]:
vgg.layers

In [5]:
# 原本
# Total params: 27,561,282
# Trainable params: 12,846,594
# Non-trainable params: 14,714,688
# BN後
# Total params: 27,563,330
# Trainable params: 12,847,618
# Non-trainable params: 14,715,712
from keras.models import Model
from keras.layers import Flatten, Dense, Dropout
from keras.layers import BatchNormalization
# trainable一定要在compile前設置
for l in vgg.layers:
    l.trainable = False
# BN: 最佳化Normalize(新的平均, 標準差網路調整出來)
x = BatchNormalization()(vgg.output)
x = Flatten()(x)
x = Dense(512, activation="relu")(x)
x = Dropout(0.25)(x)
x = Dense(2, activation="softmax")(x)
cnn = Model(inputs=vgg.input, outputs=x)
cnn.summary()

_________________________________________________________________
Layer (type)                 Output Shape              Param #   
input_1 (InputLayer)         (None, 224, 224, 3)       0         
_________________________________________________________________
block1_conv1 (Conv2D)        (None, 224, 224, 64)      1792      
_________________________________________________________________
block1_conv2 (Conv2D)        (None, 224, 224, 64)      36928     
_________________________________________________________________
block1_pool (MaxPooling2D)   (None, 112, 112, 64)      0         
_________________________________________________________________
block2_conv1 (Conv2D)        (None, 112, 112, 128)     73856     
_________________________________________________________________
block2_conv2 (Conv2D)        (None, 112, 112, 128)     147584    
_________________________________________________________________
block2_pool (MaxPooling2D)   (None, 56, 56, 128)       0         
__________

In [6]:
cnn.compile(loss="categorical_crossentropy",
            optimizer="adam",
            metrics=["accuracy"])

In [7]:
import numpy as np
# 順便偷 preprocess_input
from keras.applications.vgg16 import preprocess_input
# Pillow(PIL)
# !pip install Pillow
from keras.preprocessing.image import load_img
img = load_img("train/cat.10000.jpg", target_size=(224, 224))
img_np = np.array(img).astype("float64")
img_pre = preprocess_input(img_np)
img_pre

array([[[ -95.939, -108.779, -115.68 ],
        [ -95.939, -108.779, -115.68 ],
        [ -95.939, -108.779, -115.68 ],
        ...,
        [ -95.939, -108.779, -115.68 ],
        [ -95.939, -108.779, -115.68 ],
        [ -95.939, -108.779, -115.68 ]],

       [[ -95.939, -108.779, -115.68 ],
        [ -95.939, -108.779, -115.68 ],
        [ -95.939, -108.779, -115.68 ],
        ...,
        [ -95.939, -108.779, -115.68 ],
        [ -95.939, -108.779, -115.68 ],
        [ -95.939, -108.779, -115.68 ]],

       [[ -95.939, -108.779, -115.68 ],
        [ -95.939, -108.779, -115.68 ],
        [ -95.939, -108.779, -115.68 ],
        ...,
        [ -95.939, -108.779, -115.68 ],
        [ -95.939, -108.779, -115.68 ],
        [ -95.939, -108.779, -115.68 ]],

       ...,

       [[ -96.939, -101.779,  -41.68 ],
        [ -85.939,  -97.779,  -36.68 ],
        [ -81.939, -101.779,  -41.68 ],
        ...,
        [ -93.939, -108.779,  -96.68 ],
        [ -93.939, -108.779,  -95.68 ],
        [

In [8]:
# return_value: (原圖list, 訓練imglist, 答案list)
def get_imgs(x, y, batch):
    x = np.array(x)
    y = np.array(y)
    # random.randint(下限, 上限)
    # np.random.randint(下限, 上限+1, 你要多少個)
    idx = np.random.randint(0, len(x), batch)
    path = x[idx]

    ori_imgs = []
    pre_imgs = []
    for p in path:
        img = load_img(p, target_size=(224, 224))
        img_np = np.array(img).astype("float64")
        img_pre = preprocess_input(img_np)
        ori_imgs.append(img_np)
        pre_imgs.append(img_pre)
    targets = y[idx]
    return (np.array(ori_imgs), np.array(pre_imgs), np.array(targets))
get_imgs(df["path"], df["ans"], 10)

(array([[[[-9.56800e+01, -9.27790e+01, -8.89390e+01],
          [-9.56800e+01, -9.27790e+01, -8.89390e+01],
          [-9.56800e+01, -9.27790e+01, -8.89390e+01],
          ...,
          [-5.68000e+00, -3.87790e+01, -8.69390e+01],
          [-5.68000e+00, -3.87790e+01, -8.69390e+01],
          [-7.68000e+00, -4.07790e+01, -8.89390e+01]],
 
         [[-9.46800e+01, -9.17790e+01, -8.79390e+01],
          [-9.46800e+01, -9.17790e+01, -8.79390e+01],
          [-9.46800e+01, -9.17790e+01, -8.79390e+01],
          ...,
          [-1.06800e+01, -4.37790e+01, -9.19390e+01],
          [-6.68000e+00, -3.97790e+01, -8.79390e+01],
          [-8.68000e+00, -4.17790e+01, -8.99390e+01]],
 
         [[-9.36800e+01, -9.07790e+01, -8.69390e+01],
          [-9.36800e+01, -9.07790e+01, -8.69390e+01],
          [-9.36800e+01, -9.07790e+01, -8.69390e+01],
          ...,
          [-1.56800e+01, -4.87790e+01, -9.69390e+01],
          [-1.56800e+01, -4.87790e+01, -9.69390e+01],
          [-1.76800e+01, -5.077

In [9]:
from sklearn.model_selection import train_test_split
from keras.utils.np_utils import to_categorical
x_train, x_test, y_train, y_test = train_test_split(np.array(df["path"]),
                                                    np.array(df["ans"]),
                                                    test_size=0.2)
# 很衰的時候, 有可能y_test完全都是0, 就會轉錯, 帶入第二個參數
y_train_cat = to_categorical(y_train, 2)
y_test_cat = to_categorical(y_test, 2)
print(y_test[0], y_test_cat[0])

0 [1. 0.]


In [15]:
# train_on_batch: 自訂訓練流程
batch = 10
for i in range(10):
    _, x, y = get_imgs(x_train, y_train_cat, batch)
    loss = cnn.train_on_batch(x, y)
    print(i, "[Train Loss]:", loss)
    _, x, y = get_imgs(x_test, y_test_cat, batch)
    loss = cnn.test_on_batch(x, y)
    print(i, "[Test Loss]:", loss)

0 [Train Loss]: [1.9123058, 0.8]
0 [Test Loss]: [1.0637732, 0.9]
1 [Train Loss]: [1.1920929e-07, 1.0]
1 [Test Loss]: [2.011863, 0.8]
2 [Train Loss]: [1.6350712, 0.9]
2 [Test Loss]: [3.223619, 0.8]
3 [Train Loss]: [1.6118103, 0.9]
3 [Test Loss]: [0.8172002, 0.9]
4 [Train Loss]: [1.6739476, 0.7]
4 [Test Loss]: [1.1920929e-07, 1.0]
5 [Train Loss]: [0.38188526, 0.9]
5 [Test Loss]: [1.9858211, 0.7]
6 [Train Loss]: [1.1920929e-07, 1.0]
6 [Test Loss]: [1.1920929e-07, 1.0]
7 [Train Loss]: [1.1242056e-05, 1.0]
7 [Test Loss]: [1.6118095, 0.9]
8 [Train Loss]: [1.6118095, 0.9]
8 [Test Loss]: [2.466598, 0.8]
9 [Train Loss]: [1.1920929e-07, 1.0]
9 [Test Loss]: [1.8015182, 0.8]


In [11]:
cnn.predict(x)

array([[1.00000000e+00, 1.44901235e-11],
       [8.13774477e-06, 9.99991894e-01],
       [2.29698199e-23, 1.00000000e+00],
       [0.00000000e+00, 1.00000000e+00],
       [1.32435432e-03, 9.98675644e-01],
       [2.73970943e-20, 1.00000000e+00],
       [4.64012563e-13, 1.00000000e+00],
       [5.37026591e-23, 1.00000000e+00],
       [1.00000000e+00, 1.33627507e-16],
       [3.67105876e-22, 1.00000000e+00]], dtype=float32)

In [16]:
imgs, testx, testy = get_imgs(x_test, y_test_cat, 200)
cnn.evaluate(testx, testy)

200/200 [==============================] - 68s 338ms/step


[0.873725204240909, 0.925]

In [18]:
# Model:(X Sequential) 沒有predict_classes
# predict + argmax(axis=1)
cnn.predict(x).argmax(axis=1)

array([1, 1, 0, 0, 1, 0, 1, 0, 0, 0])